name: Ansible Playbook
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ratosos/ansible-playbook-docker-action:master
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
        AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
    steps:
      - uses: actions/checkout@v2
      - run: |
         chmod +x entrypoint.sh
         ./entrypoint.sh
