name: Ansible Playbook
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ratosos/ansible-playbook-docker-action:master
      env:
        AZURE_SUB: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLI: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SEC: ${{ secrets.AZURE_SECRET }}
        AZURE_TEN: ${{ secrets.AZURE_TENANT }}
    steps:
      - run: |
         echo $AZURE_SUB
         echo It runs in the container instead of the VM.

#jobs:
#  ansible_playbook_job:
#    runs-on: ubuntu-latest
#    name: Execute Sample Playbook
#    steps:
#      - uses: actions/checkout@v1
#      - name: Execute Playbook Action Step
#        id: Execution
#        uses: Ratosos/ansible-playbook-docker-action@master
#        env:
#          ANSIBLE_STDOUT_CALLBACK: debug
#          ANSIBLE_FORCE_COLOR: true
#        with:
#          playbookName: "Ansible/Playbook/create_linux.yml"
##          inventoryFile: ".ansible/inventory/local.yml"
#          requirementsFile: "Ansible/requirements.yml"
##          rolesPath: ".ansible/playbooks/roles"
##          keyFile: ".ansible/random-ssh-key.pem"
##          keyFileVaultPass: ${{ secrets.KEYFILE_VAULT_PASS }}
##          extraFile: "Ansible/extra.yml"
##          extraVars: "-e my_first_extra=${{ github.actor }} -e my_second_one=${{ github.sha }}"
#          AZURE_SUB: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          AZURE_CLI: ${{ secrets.AZURE_CLIENT_ID }}
#          AZURE_SEC: ${{ secrets.AZURE_SECRET }}
#          AZURE_TEN: ${{ secrets.AZURE_TENANT }}
#          verbosity: "vvv"
